# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-256.0.dev <4.0.0"

dependencies:
  analyzer: ^6.2.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_phoenix: ^1.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  nylo_framework: ^5.27.6
  openid_client: ^0.4.8
  pretty_dio_logger: ^1.3.1
  syncfusion_flutter_charts: ^26.2.14
  url_launcher: ^6.3.0
  zoom_widget: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
  #  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_secure_storage: 9.0.0

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env
  fonts:
    - family: Tinkoff-Sans
      fonts:
        - asset: public/assets/fonts/T.ttf
        - asset: public/assets/fonts/TB.ttf
        - asset: public/assets/fonts/TM.ttf
